### ISSUE TITLE
Evennia instances running on 0.7 send `connected_account_count` and `total_account_count`

### ISSUE THREAD

**Issue by aliceafterall** [gtaylor/evennia-game-index#3]
Evennia instances running on 0.7 send `connected_account_count` and `total_account_count` instead of what the server is expecting - `connected_player_count` and `total_player_count`. This causes the `None` values in the game listing.

## How to Fix
Evennia could change back to the expected values, or we could add arguments to the parser to cover the new keys.

**Comment by Griatch** [comment]
Ah, of course! The correct approach would be to update the game index; `total_account_count` is the more correct thing for 0.7. But it would make sense to support both old and new for now.

**Comment by aliceafterall** [comment]
My thinking was to add them as parser arguments, but they seem to override the previous. I'll have to have a check for the old ones, I suppose. I'll submit a PR this morning, and @gtaylor can see if there's a better way!

**Comment by aliceafterall** [comment]
PR #4 addresses this - hopefully it's an acceptable solution! Both types of keys work - I tested with the development server for appengine.
